### ISSUE TITLE
Reactivating the WG

### ISSUE THREAD

**Issue by HaoZeke** [mpiwg-fortran/fortran-issues#1]
FYI: https://fortran-lang.discourse.group/t/mpi-fortran-working-group/3755

What would be required to reactivate the WG?

**Comment by wesbland** [comment]
A working group can be reactivated at any time if people are interested in the topic and have things to discuss. If there are any concerns, suggestions, etc., I would recommend raising them on the working group's [mailing list](https://lists.mpi-forum.org/mailman/listinfo/mpiwg-fortran), which, while low volume, has a large number of knowledgeable and responsive participants.
